"""empty message

Revision ID: 87436f6d742e
Revises: f2a8b7c9d1e3
Create Date: 2026-07-23 00:18:14.253379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87436f6d742e'
down_revision: Union[str, None] = 'f2a8b7c9d1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_uuid', sa.String(length=100), nullable=False, comment='上传会话 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传用户'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='所属检测场景'),
    sa.Column('model_version_id', sa.Integer(), nullable=True, comment='上传完成后生成的模型版本 ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='模型版本'),
    sa.Column('model_type', sa.String(length=50), nullable=False, comment='YOLO 模型类型'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='INITIATED/UPLOADING/UPLOADED/FAILED/EXPIRED/CANCELLED'),
    sa.Column('bucket', sa.String(length=128), nullable=False, comment='OSS bucket'),
    sa.Column('object_key', sa.String(length=500), nullable=False, comment='模型权重对象 key'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='上传对象 MIME 类型'),
    sa.Column('expected_size', sa.BigInteger(), nullable=True, comment='客户端声明大小'),
    sa.Column('actual_size', sa.BigInteger(), nullable=True, comment='OSS HeadObject 大小'),
    sa.Column('etag', sa.String(length=128), nullable=True, comment='OSS 对象 ETag'),
    sa.Column('checksum_sha256', sa.String(length=128), nullable=True, comment='模型 SHA256'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='上传元数据'),
    sa.Column('client_completed_at', sa.DateTime(), nullable=True, comment='客户端完成合并时间'),
    sa.Column('server_verified_at', sa.DateTime(), nullable=True, comment='服务端校验通过时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='上传会话过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_uploads_model_version_id'), 'model_uploads', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_model_uploads_scene_id'), 'model_uploads', ['scene_id'], unique=False)
    op.create_index(op.f('ix_model_uploads_status'), 'model_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_model_uploads_upload_uuid'), 'model_uploads', ['upload_uuid'], unique=True)
    op.create_index(op.f('ix_model_uploads_user_id'), 'model_uploads', ['user_id'], unique=False)
    op.alter_column('dataset_uploads', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='INITIATED/UPLOADING/UPLOADED/FAILED/EXPIRED/CANCELLED',
               existing_comment='INITIATED/CLIENT_COMPLETED/UPLOADED/PROCESSING/READY/FAILED',
               existing_nullable=False)
    op.alter_column('dataset_uploads', 'server_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='服务端收到 OSS 完成事件或后续 HeadObject 校验通过时间',
               existing_comment='服务端 HeadObject 校验通过时间',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment='本地模型文件路径或 OSS URI',
               existing_comment='本地模型文件路径')
    op.alter_column('remote_training_jobs', 'dataset_upload_id',
               existing_type=sa.INTEGER(),
               comment='已由 OSS 完成事件确认的 UPLOADED 数据集上传记录',
               existing_comment='READY 数据集上传记录',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remote_training_jobs', 'dataset_upload_id',
               existing_type=sa.INTEGER(),
               comment='READY 数据集上传记录',
               existing_comment='已由 OSS 完成事件确认的 UPLOADED 数据集上传记录',
               existing_nullable=False)
    op.alter_column('model_versions', 'model_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='本地模型文件路径',
               existing_comment='本地模型文件路径或 OSS URI')
    op.alter_column('dataset_uploads', 'server_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='服务端 HeadObject 校验通过时间',
               existing_comment='服务端收到 OSS 完成事件或后续 HeadObject 校验通过时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='INITIATED/CLIENT_COMPLETED/UPLOADED/PROCESSING/READY/FAILED',
               existing_comment='INITIATED/UPLOADING/UPLOADED/FAILED/EXPIRED/CANCELLED',
               existing_nullable=False)
    op.drop_index(op.f('ix_model_uploads_user_id'), table_name='model_uploads')
    op.drop_index(op.f('ix_model_uploads_upload_uuid'), table_name='model_uploads')
    op.drop_index(op.f('ix_model_uploads_status'), table_name='model_uploads')
    op.drop_index(op.f('ix_model_uploads_scene_id'), table_name='model_uploads')
    op.drop_index(op.f('ix_model_uploads_model_version_id'), table_name='model_uploads')
    op.drop_table('model_uploads')
    # ### end Alembic commands ###
