"""init: create users, detection_records, training_tasks tables

Revision ID: a50079ca061d
Revises: d9fd147ac4ff
Create Date: 2026-07-07 14:03:34.503957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50079ca061d'
down_revision: Union[str, None] = 'd9fd147ac4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
