"""init: create users, detection_records, training_tasks tables

Revision ID: d9fd147ac4ff
Revises: 
Create Date: 2026-07-07 11:15:25.129548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fd147ac4ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码，如 detection:task:create'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块：auth/detection/training/agent/system'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='权限描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色标识，如 admin/operator/viewer'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='角色显示名，如 管理员/操作员/访客'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='角色描述'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统内置角色（不可删除）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像 URL'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级管理员'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('session_uuid', sa.String(length=100), nullable=False, comment='会话唯一标识'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题（取第一条消息摘要）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/archived'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='消息数量'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_uuid'), 'chat_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('detection_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='场景标识，如 remote_sensing'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='场景显示名，如 遥感目标检测'),
    sa.Column('description', sa.Text(), nullable=True, comment='场景描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='场景分类：agriculture/industry/remote_sensing/medical/traffic'),
    sa.Column('class_names', sa.JSON(), nullable=False, comment='类别列表，如 ["airplane","storage-tank"]'),
    sa.Column('class_names_cn', sa.JSON(), nullable=True, comment='类别中文名映射，如 {"airplane":"飞机"}'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户（可为空表示系统操作）'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='冗余用户名，方便查询'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='操作模块：auth/detection/training/agent/system'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型：create/update/delete/login/export'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='操作对象类型：user/task/model/session'),
    sa.Column('target_id', sa.String(length=100), nullable=True, comment='操作对象 ID'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='操作描述'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='客户端 IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='客户端 User-Agent'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP 方法'),
    sa.Column('request_path', sa.String(length=500), nullable=True, comment='请求路径'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='操作结果：success/failure'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user/assistant/tool/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('agent_used', sa.String(length=50), nullable=True, comment='处理的 Agent：supervisor/detection/analysis/qa'),
    sa.Column('tool_calls', sa.JSON(), nullable=True, comment='工具调用记录，如 [{"tool":"detect_objects","args":{...}}]'),
    sa.Column('tool_result', sa.Text(), nullable=True, comment='工具调用返回结果'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Token 消耗量'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='响应耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作用户'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='关联场景'),
    sa.Column('task_uuid', sa.String(length=100), nullable=False, comment='任务唯一标识'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/running/completed/failed/cancelled'),
    sa.Column('model_name', sa.String(length=50), nullable=True, comment='基础模型：yolov11n/s/m/l/x'),
    sa.Column('epochs', sa.Integer(), nullable=True, comment='训练轮数'),
    sa.Column('img_size', sa.Integer(), nullable=True, comment='图像尺寸'),
    sa.Column('batch_size', sa.Integer(), nullable=True, comment='批次大小'),
    sa.Column('device', sa.String(length=20), nullable=True, comment='训练设备：0/1/cpu'),
    sa.Column('optimizer', sa.String(length=20), nullable=True, comment='优化器：SGD/Adam/AdamW'),
    sa.Column('lr0', sa.Float(), nullable=True, comment='初始学习率'),
    sa.Column('augment_config', sa.JSON(), nullable=True, comment='数据增强配置'),
    sa.Column('current_epoch', sa.Integer(), nullable=True, comment='当前轮数'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='进度百分比 0~100'),
    sa.Column('dataset_path', sa.String(length=500), nullable=True, comment='数据集路径'),
    sa.Column('dataset_size', sa.Integer(), nullable=True, comment='数据集图像数量'),
    sa.Column('data_yaml', sa.String(length=500), nullable=True, comment='data.yaml 路径'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始训练时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='训练完成时间'),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_tasks_scene_id'), 'training_tasks', ['scene_id'], unique=False)
    op.create_index(op.f('ix_training_tasks_task_uuid'), 'training_tasks', ['task_uuid'], unique=True)
    op.create_index(op.f('ix_training_tasks_user_id'), 'training_tasks', ['user_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='所属场景'),
    sa.Column('training_task_id', sa.Integer(), nullable=True, comment='来源训练任务（可为空，支持手动上传）'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号，如 v1.0.0'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('model_type', sa.String(length=50), nullable=True, comment='模型类型：yolov11n/s/m/l/x'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/archived/deleted'),
    sa.Column('model_path', sa.String(length=500), nullable=False, comment='本地模型文件路径'),
    sa.Column('minio_url', sa.String(length=500), nullable=True, comment='MinIO 存储 URL'),
    sa.Column('map50', sa.Float(), nullable=True, comment='mAP@0.50'),
    sa.Column('map50_95', sa.Float(), nullable=True, comment='mAP@0.50:0.95'),
    sa.Column('precision', sa.Float(), nullable=True, comment='精确率'),
    sa.Column('recall', sa.Float(), nullable=True, comment='召回率'),
    sa.Column('per_class_ap', sa.JSON(), nullable=True, comment='各类别 AP，如 {"airplane":0.85,"tank":0.72}'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本描述/变更说明'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='模型文件大小（字节）'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为该场景的默认模型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['training_task_id'], ['training_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_scene_id'), 'model_versions', ['scene_id'], unique=False)
    op.create_table('training_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='所属训练任务'),
    sa.Column('epoch', sa.Integer(), nullable=False, comment='当前轮数'),
    sa.Column('box_loss', sa.Float(), nullable=True, comment='边界框损失'),
    sa.Column('cls_loss', sa.Float(), nullable=True, comment='分类损失'),
    sa.Column('dfl_loss', sa.Float(), nullable=True, comment='DFL 损失'),
    sa.Column('precision', sa.Float(), nullable=True, comment='精确率'),
    sa.Column('recall', sa.Float(), nullable=True, comment='召回率'),
    sa.Column('map50', sa.Float(), nullable=True, comment='mAP@0.50'),
    sa.Column('map50_95', sa.Float(), nullable=True, comment='mAP@0.50:0.95'),
    sa.Column('lr', sa.Float(), nullable=True, comment='当前学习率'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['training_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_metrics_task_id'), 'training_metrics', ['task_id'], unique=False)
    op.create_table('detection_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作用户'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='使用的检测场景'),
    sa.Column('model_version_id', sa.Integer(), nullable=True, comment='使用的模型版本'),
    sa.Column('task_type', sa.String(length=20), nullable=False, comment='检测类型：single/batch/folder/video/camera'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/processing/completed/failed'),
    sa.Column('total_images', sa.Integer(), nullable=True, comment='处理图像总数'),
    sa.Column('total_objects', sa.Integer(), nullable=True, comment='检测到目标总数'),
    sa.Column('total_inference_time', sa.Float(), nullable=True, comment='总推理耗时（ms）'),
    sa.Column('conf_threshold', sa.Float(), nullable=True, comment='置信度阈值'),
    sa.Column('iou_threshold', sa.Float(), nullable=True, comment='NMS IoU 阈值'),
    sa.Column('image_size', sa.Integer(), nullable=True, comment='推理图像尺寸'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('analysis_report', sa.Text(), nullable=True, comment='分析报告（Markdown 格式）'),
    sa.Column('analysis_suggestion', sa.Text(), nullable=True, comment='专业建议'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级：low/medium/high/critical'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True, comment='分析完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_tasks_created_at'), 'detection_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_tasks_scene_id'), 'detection_tasks', ['scene_id'], unique=False)
    op.create_index(op.f('ix_detection_tasks_user_id'), 'detection_tasks', ['user_id'], unique=False)
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='所属检测任务'),
    sa.Column('image_path', sa.String(length=500), nullable=False, comment='原始图像路径'),
    sa.Column('annotated_image_url', sa.String(length=500), nullable=True, comment='标注图像 MinIO URL'),
    sa.Column('class_name', sa.String(length=50), nullable=False, comment='类别名称'),
    sa.Column('class_name_cn', sa.String(length=50), nullable=True, comment='类别中文名'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='类别 ID'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 0~1'),
    sa.Column('bbox', sa.JSON(), nullable=False, comment='边界框 [x1, y1, x2, y2]'),
    sa.Column('inference_time', sa.Float(), nullable=True, comment='该图推理耗时（ms）'),
    sa.Column('image_width', sa.Integer(), nullable=True, comment='图像宽度'),
    sa.Column('image_height', sa.Integer(), nullable=True, comment='图像高度'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['detection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_class_name'), 'detection_results', ['class_name'], unique=False)
    op.create_index(op.f('ix_detection_results_task_id'), 'detection_results', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_results_task_id'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_class_name'), table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index(op.f('ix_detection_tasks_user_id'), table_name='detection_tasks')
    op.drop_index(op.f('ix_detection_tasks_scene_id'), table_name='detection_tasks')
    op.drop_index(op.f('ix_detection_tasks_created_at'), table_name='detection_tasks')
    op.drop_table('detection_tasks')
    op.drop_index(op.f('ix_training_metrics_task_id'), table_name='training_metrics')
    op.drop_table('training_metrics')
    op.drop_index(op.f('ix_model_versions_scene_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_training_tasks_user_id'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_task_uuid'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_scene_id'), table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('detection_scenes')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_uuid'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
