"""

Revision ID: de4dfb51c437
Revises: 6a4cf9661f10
Create Date: 2026-07-18 10:57:15.929360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de4dfb51c437'
down_revision: Union[str, None] = '6a4cf9661f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_uploads', 'scene_id',
               existing_type=sa.INTEGER(),
               comment='关联检测场景，可为空表示尚未绑定业务场景',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               comment='上传对象 MIME 类型',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'etag',
               existing_type=sa.VARCHAR(length=128),
               comment='OSS 对象 ETag',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'checksum_sha256',
               existing_type=sa.VARCHAR(length=128),
               comment='客户端或后端计算的 SHA256',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'client_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='客户端声明上传完成时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'server_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='服务端 HeadObject 校验通过时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'ready_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='数据集可用于训练的时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'preprocessing_job_id',
               existing_type=sa.VARCHAR(length=128),
               comment='数据预处理 PAI-DLC Job ID',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'error_message',
               existing_type=sa.TEXT(),
               comment='失败原因',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='上传会话过期时间',
               existing_nullable=False)
    op.drop_constraint('uq_dataset_uploads_bucket_raw_key', 'dataset_uploads', type_='unique')
    op.alter_column('model_artifact_locations', 'bucket',
               existing_type=sa.VARCHAR(length=128),
               comment='OSS/MinIO bucket',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'object_key',
               existing_type=sa.VARCHAR(length=500),
               comment='OSS/MinIO 对象 key',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'local_path',
               existing_type=sa.VARCHAR(length=500),
               comment='服务端本地缓存路径',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'url',
               existing_type=sa.VARCHAR(length=1000),
               comment='对象 URI 或可访问 URL',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               comment='文件 MIME 类型',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'file_size',
               existing_type=sa.BIGINT(),
               comment='文件大小',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'etag',
               existing_type=sa.VARCHAR(length=128),
               comment='对象存储 ETag',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'checksum_sha256',
               existing_type=sa.VARCHAR(length=128),
               comment='文件 SHA256',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'workspace_id',
               existing_type=sa.VARCHAR(length=128),
               comment='PAI 工作空间 ID',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'resource_id',
               existing_type=sa.VARCHAR(length=128),
               comment='PAI 资源配额 ID，可为空',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'dlc_job_id',
               existing_type=sa.VARCHAR(length=128),
               comment='PAI-DLC Job ID',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'remote_status',
               existing_type=sa.VARCHAR(length=30),
               comment='CREATED/SUBMITTED/QUEUED/RUNNING/SUCCEEDED/FAILED/STOPPED',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'region',
               existing_type=sa.VARCHAR(length=64),
               comment='PAI-DLC 地域',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'image_uri',
               existing_type=sa.VARCHAR(length=500),
               comment='训练镜像完整地址',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               comment='DLC Job 类型',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'ecs_spec',
               existing_type=sa.VARCHAR(length=100),
               comment='公共资源 ECS 规格',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'pod_count',
               existing_type=sa.INTEGER(),
               comment='Worker Pod 数量',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'user_command',
               existing_type=sa.TEXT(),
               comment='容器内执行的训练命令',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'envs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='注入训练容器的环境变量',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'input_dataset_prefix',
               existing_type=sa.VARCHAR(length=500),
               comment='输入数据集 OSS 前缀',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'output_prefix',
               existing_type=sa.VARCHAR(length=500),
               comment='训练输出 OSS 前缀',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'results_csv_key',
               existing_type=sa.VARCHAR(length=500),
               comment='results.csv 对象 key',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'best_weight_key',
               existing_type=sa.VARCHAR(length=500),
               comment='best.pt 对象 key',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'success_key',
               existing_type=sa.VARCHAR(length=500),
               comment='_SUCCESS 对象 key',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'callback_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='回调 token SHA256',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='CreateJob 成功提交时间',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='最近一次轮询同步时间',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='远程任务完成或停止时间',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'error_message',
               existing_type=sa.TEXT(),
               comment='远程任务失败原因',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remote_training_jobs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='远程任务失败原因',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='远程任务完成或停止时间',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='最近一次轮询同步时间',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='CreateJob 成功提交时间',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'callback_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='回调 token SHA256',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'success_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='_SUCCESS 对象 key',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'best_weight_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='best.pt 对象 key',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'results_csv_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='results.csv 对象 key',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'output_prefix',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='训练输出 OSS 前缀',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'input_dataset_prefix',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='输入数据集 OSS 前缀',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'envs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='注入训练容器的环境变量',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'user_command',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='容器内执行的训练命令',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'pod_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Worker Pod 数量',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'ecs_spec',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='公共资源 ECS 规格',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='DLC Job 类型',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'image_uri',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='训练镜像完整地址',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'region',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='PAI-DLC 地域',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'remote_status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='CREATED/SUBMITTED/QUEUED/RUNNING/SUCCEEDED/FAILED/STOPPED',
               existing_nullable=False)
    op.alter_column('remote_training_jobs', 'dlc_job_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='PAI-DLC Job ID',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'resource_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='PAI 资源配额 ID，可为空',
               existing_nullable=True)
    op.alter_column('remote_training_jobs', 'workspace_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='PAI 工作空间 ID',
               existing_nullable=False)
    op.alter_column('model_artifact_locations', 'checksum_sha256',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='文件 SHA256',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'etag',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='对象存储 ETag',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'file_size',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='文件大小',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='文件 MIME 类型',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='对象 URI 或可访问 URL',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'local_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='服务端本地缓存路径',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'object_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='OSS/MinIO 对象 key',
               existing_nullable=True)
    op.alter_column('model_artifact_locations', 'bucket',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='OSS/MinIO bucket',
               existing_nullable=True)
    op.create_unique_constraint('uq_dataset_uploads_bucket_raw_key', 'dataset_uploads', ['bucket', 'raw_object_key'])
    op.alter_column('dataset_uploads', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='上传会话过期时间',
               existing_nullable=False)
    op.alter_column('dataset_uploads', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='失败原因',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'preprocessing_job_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='数据预处理 PAI-DLC Job ID',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'ready_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='数据集可用于训练的时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'server_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='服务端 HeadObject 校验通过时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'client_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='客户端声明上传完成时间',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'checksum_sha256',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='客户端或后端计算的 SHA256',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'etag',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='OSS 对象 ETag',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='上传对象 MIME 类型',
               existing_nullable=True)
    op.alter_column('dataset_uploads', 'scene_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联检测场景，可为空表示尚未绑定业务场景',
               existing_nullable=True)
    # ### end Alembic commands ###
